### PR TITLE
Update Web NFC feature

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Web NFC has changed quite a lot lately and will be in origin trial in Chrome [soon](https://github.com/w3ctag/design-reviews/issues/461). This PR makes sure the old implementation is updated to match new spec.

I've tried it locally and it works like a charm!

FYI @kenchris @zolkis @riju

Please review @NOtherDev
Thanks!

### CODE REVIEW

**Comment by NOtherDev** [comment]
Great, thanks! 👍 
 I'll merge it in when I deploy the new version of the site, this year hopefully.

**Comment by beaufortfrancois** [comment]
> I'll merge it in when I deploy the new version of the site, this year hopefully.

If you need help testing the new version, let me know.

**Comment by beaufortfrancois** [comment]
@NOtherDev We're about to start an origin trial for Web NFC and I was wondering how close we were from having Web NFC documentation updated in https://whatwebcando.today/

**Comment by NOtherDev** [comment]
@beaufortfrancois We're close, I'm almost ready, I'd expect the update to happen next week the latest.

**Comment by beaufortfrancois** [comment]
Looking forward to it!

**Comment by NOtherDev** [comment]
@beaufortfrancois [Sneak peek](https://wwcd-beta.surge.sh/nfc.html). Going to publish the update on Wed (few more tests needed).

**Comment by NOtherDev** [comment]
Published. Thanks a lot @beaufortfrancois!

**Comment by beaufortfrancois** [comment]
Woohoo! https://whatwebcando.today/nfc.html

**Pull request closed without merging**
